language: node_js
node_js:
- 8
notifications:
  slack:
    secure: 4UVgf5ASzZNU/KLx3FQPx7yGdHgtwE5jKvQI6oZVOCR1ZPu/iv3CKWryzeEI5A7T0i4HZ1rZHsyu9CBwt5ACg49kmxErzHjHGqKSxznz3UkU5pnCzchRMYsQ8IMH4T0Pfqb9cL6/ffytPgbFYKN/IEcVPZfR6/YFT9B+2F9JIbYNvdlNy3kLiCU8ZTJrlzdDHHAAAW7T4MSNCd1l9XTfNIBeRoz+jDA8HU5JC+G4X5Uq1uVxORN85+DchG6k+WxVWZ/ovKsaBGdb5wYMqd3krmPgLkX3+qffobzPYnew7XH7UF2GFKxl7FKggCeasF5lracxElOXihHyaaOMwFC9alOHFIuTHbL3G/LLBFP1lXpk45cxuqOd0yjg+/gOq1idxFFCP+cuyOldVe1RaosKst1n8QPGLINSR5fr1QIszty4DdGa0O8YwkybOXACMUt/CR5uBg9MY+3Mm9vScqRJWBeZr2zDdt52KPhQhW6W2F1OBxjMTfbbAQqVx2wQTYD0JI0/RsqUBHy683iyTJ88mPnYNj2L8eVUA9n6fMpB/hWlullQMUGtwFNF1YQDRjZyxRZMOM++VU9ZtoPS4e7ZtiKJD5xfVz570dwCZlnEs4QTHlVQKoUmoGPQtVJfjazAOJ8VoGF6+ONK0BYMUgpvCDMk3xjOficUQnaD4SJcZjA=
